### ISSUE TITLE
install hook: No such file or directory

### ISSUE THREAD

**Issue by miteyema** [captainhookphp/hook-installer#3]
It seems there is problem when there are spaces in the `config.php-path`.
This happens for example when using Herd on Mac for managing different PHP versions.
There will be a space between Application and Support in the full path name:

`captainhook.json`

``` json
{
    "config": {
        "php-path": "/Users/username/Library/Application Support/Herd/bin//php"
    },

}
```

- No problems when running `vendor/bin/captainhook install`
- When adding  the hook-installer via `composer require --dev captainhook/hook-installer`, it will fail:

```
CaptainHook Hook Installer
  - Detect executable: /Users/username/Documents/Code/my-php-project/vendor/bin/captainhook
  - Detect configuration: captainhook.json
  - Install hooks: sh: /Users/username/Library/Application: No such file or directory

In ComposerPlugin.php line 257:
                                                                                                 
  Shiver me timbers! CaptainHook could not install yer git hooks! (installation process failed) 
```

One sees the full path being used cuts off after the space in the folder name, i.e. 
- incorrectly using `sh: /Users/username/Library/Application`
- and thus not using  `sh: /Users/username/Library/Application Support/Herd/bin//php`

**Comment by sebastianfeldmann** [comment]
Fixed in version `1.0.3` big thanks to @Sm1lEE
